version: '3.7'

# Generate a services using nestjs and postgress stack with dev mode
services:
  app:
    container_name: app
    build:
      context: .docker/
      dockerfile: Dockerfile
    entrypoint: .docker/entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - postgres

  postgres:
    container_name: database
    image: postgres:16-alpine
    restart: always
    tty: true
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_ADDR: 0.0.0.0
volumes:
  postgres-data:
